# Configuración de la reclamación del volumen persistente
apiVersion: v1

# Establecer tipo PersistentVolumeClaim
kind: PersistentVolumeClaim

# Metadatos del PVC
metadata:

  # Asignar nombre
  name: myvol

  # Asignar etiqueta
  labels:
    componente: myvol

# Especificaciones del PVC
spec:

  # Solicitud de volumen accesible por un único nodo en modo lectura y escritura
  accessModes:
    - ReadWriteOnce
  
  # Solicitud de volumen con 100MB de capacidad
  resources:
    requests:
      storage: 100Mi

# Autora: Naiara Benito Balbás
